### PR TITLE
fix: working sample 04

### LINKED ISSUE #86: Transfer Sample 04 terminating immediately after startup
# Bug Report

## Describe the Bug
A few seconds after completing the docker-compose, a failing http request in the the provider_1 container causes this container to terminate. 

### Expected Behavior
All containers should stay up and running. 

### Observed Behavior
A few seconds after completing the docker-compose, a failing http request in the the provider_1 container causes this container to terminate. The other containers are then terminating as well (like they should in such as case, since we are using the "--abort-on-container-exit" parameter). 

## Steps to Reproduce
1. Clone the Samples Project from Github.
2. Configure, build and run Sample No. 1 as described in the README. (Everything is working just fine here)
3. Download opentelemetry agent. Copy this file to the Sample04 root folder. (As instructed by the README)
4. Build Sample04 (of course using the given Gradle Wrapper)
5. Run docker-compose as specified in the README. 

## Context Information

Xubuntu 22.04  
Docker version 24.0.4, build 3713ee1
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)

## Detailed Description
I have attached the logging output here:  
[log.txt](https://github.com/eclipse-edc/Samples/files/12011317/log.txt)

## Possible Implementation
None that I know of.

### PR DESCRIPTION
**Pull request by matthiasdg**
## What this PR changes/adds

fixes #86; commands from README now work.

## Why it does that

basically looked at transfer sample 01 and applied all dependencies/variables from there

## Further notes
first experience with edc connector, so not sure if everything now behaves as it should. transfer happens + jaeger + prometheus work

## Linked Issue(s)

Closes #86

## Checklist

- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] documented code?
- [ ] assigned appropriate label?
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Samples/blob/main/CONTRIBUTING.md#submit-a-pull-request) for details_) -> **ENDS IN 404**

### CODE REVIEW

**Review by ndr-brt — COMMENTED** [review]
Hey, thanks for the contribution, since you are here, could you take care on adding an integration test in the same way other samples are tested? so we'd avoid regressions in the future

**Comment by matthiasdg** [comment]
@ndr-brt to have an integration test that covers the differences with the `transfer-01` sample requires including the docker-compose in the test.

As an experiment I did that, using the `testcontainers` framework. Note that running this test requires the downloaded opentelemetry-javaagent as per the README + docker-compose on the local machine. (Without docker-compose is also an option, but that seems to require a very large heap space, did not get there).

Other than that, the test is almost identical to the `transfer-01` test. I did not run `assertTransferProcessStatusConsumerSide`, since there is actually also an error like `No checker found for process 2bfb0f52-15f4-4028-8337-ccd1c4144de1. The process will not advance to the COMPLETED state.`. Not sure if this is related to https://github.com/eclipse-edc/Connector/issues/3334 or due to some missing configuration

**Review by ndr-brt — COMMENTED** [review]
test is broke because it expects to find the agent jar, but it doesn't

**Comment by matthiasdg** [comment]
Yes, I put that in the comment. If you want to have a test like this and don't want to check in this file (README already mentioned the manual download), maybe can be downloaded from the github action. Also not sure whether this will run on a github actions runner.
The `waitingFor` can probably also use some improvement

**Comment by ndr-brt** [comment]
@matthiasdg We could have it downloaded by gradle [as it has been implemented by tractusx](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/build.gradle.kts#L156-L174)

**Comment by Jens011203** [comment]
Hello, the issue is still not solved. If you have time, it would be nice if you could commit the code to the main branch.😀

**Comment by ndr-brt** [comment]
@matthiasdg we were near to the solution, could you take care of fixing the CI? I will merge then

**Pull request closed without merging**
